import random
from character_generator import run_generator, ALL_CLASSES


# ============================================================
# HELPERS
# ============================================================

def roll_alignment():
    """1–2 Lawful, 3–5 Neutral, 6 Chaotic."""
    r = random.randint(1, 6)
    if r <= 2:
        return "Lawful"
    elif r <= 5:
        return "Neutral"
    return "Chaotic"


def allowed_alignments(base_alignment):
    """
    Drużyna może mieć alignment w zakresie ±1 kroku:
    Lawful ↔ Neutral ↔ Chaotic
    """
    if base_alignment == "Lawful":
        return ["Lawful", "Neutral"]
    if base_alignment == "Neutral":
        return ["Lawful", "Neutral", "Chaotic"]
    if base_alignment == "Chaotic":
        return ["Neutral", "Chaotic"]


def roll_party_size():
    return random.randint(1, 4) + 2  # 1d4+2


def roll_individual_level(base_level):
    """
    Tabela:
    1 → base-2
    2 → base-1
    3-4 → base
    5 → base+1
    6 → base+2
    """
    r = random.randint(1, 6)

    if r == 1:
        lvl = base_level - 2
    elif r == 2:
        lvl = base_level - 1
    elif r in (3, 4):
        lvl = base_level
    elif r == 5:
        lvl = base_level + 1
    else:
        lvl = base_level + 2

    return max(1, lvl)


def maybe_replace_with_henchmen(level):
    """
    50% chance → replace adventurer with two henchmen
    Only applies for characters level 3 or higher.
    Henchmen level = level - 2 (minimum 1)
    """
    # Only adventurers level 3+ can be replaced
    if level < 3:
        return False, None

    # 50% chance
    if random.random() < 0.5:
        hench_level = max(1, level - 2)
        return True, hench_level

    return False, None


# ============================================================
# MAIN GENERATOR
# ============================================================

def generate_rival_party(location_type, dungeon_level=None, wilderness_max=None, settlement_class=None):
    """
    location_type: 'dungeon', 'wilderness', 'settlement'
    dungeon_level: int
    wilderness_max: int
    settlement_class: 1–6
    """

    # 1) Party size
    party_size = roll_party_size()

    # 2) Party alignment
    party_alignment = roll_alignment()
    allowed = allowed_alignments(party_alignment)

    # 3) Base level depending on environment
    if location_type == "dungeon":
        base_level = dungeon_level
    elif location_type == "wilderness":
        base_level = wilderness_max
    elif location_type == "settlement":
        base_level = max(1, 7 - settlement_class)
    else:
        raise ValueError("location_type must be dungeon/wilderness/settlement")

    members = []

    for _ in range(party_size):

        # 4) Roll individual level
        lvl = roll_individual_level(base_level)

        # 5) 50% chance to replace adventurer with two henchmen
        replaced, hench_level = maybe_replace_with_henchmen(lvl)

        if replaced:
            # Two henchmen
            for _h in range(2):
                final_class = random.choice(list(ALL_CLASSES))
                alignment = random.choice(allowed)

                result = run_generator(final_class, hench_level, mode="heroic", style="sword_and_sorcery")

                members.append({
                    "type": "henchman",
                    "class": final_class,
                    "level": hench_level,
                    "alignment": alignment,
                    "output": result
                })

        else:
            # Full adventurer
            final_class = random.choice(list(ALL_CLASSES))
            alignment = random.choice(allowed)

            result = run_generator(final_class, lvl, mode="heroic", style="sword_and_sorcery")

            members.append({
                "type": "adventurer",
                "class": final_class,
                "level": lvl,
                "alignment": alignment,
                "output": result
            })

    return {
        "party_alignment": party_alignment,
        "allowed_alignments": allowed,
        "party_size": party_size,
        "base_level": base_level,
        "members": members
    }


# ============================================================
# PRETTY PRINT
# ============================================================

def format_rival_party(party):
    lines = []

    # --- Party header ---
    lines.append("=== RIVAL ADVENTURING PARTY ===")
    lines.append(f"Party alignment: {party['party_alignment']}")
    lines.append(f"Base level: {party['base_level']}")
    lines.append("")

    # --- Each member ---
    for idx, m in enumerate(party["members"], start=1):
        tag = " (Henchman)" if m["type"] == "henchman" else ""

        # Output generated by run_generator() is already well formatted
        # so we simply embed it as-is.
        lines.append(m["output"])
        lines.append("\n--------------------------------------------\n")

    return "\n".join(lines)
